version: 2.1

orbs:
  general: edahlseng/general@1.22.0

workflows:
  main:
    jobs:
      - general/install-dependencies-npm
      - general/lint-commit:
          requires:
            - general/install-dependencies-npm
      - general/lint-js:
          requires:
            - general/install-dependencies-npm
      - general/lint-json:
          requires:
            - general/install-dependencies-npm
      - general/lint-yaml:
          requires:
            - general/install-dependencies-npm
      - general/validate-js:
          requires:
            - general/install-dependencies-npm
      - general/build:
          executor: general/node
          requires:
            - general/install-dependencies-npm
      - general/test:
          executor: general/node
          requires:
            - general/build
      - general/create-release-pr:
          context: Release Bot
          git-ssh-fingerprint: 56:0f:82:9f:20:b1:3d:5e:03:b9:fe:40:b6:31:15:10
          git-user-email: edahlseng@users.noreply.github.com
          git-user-name: "Release Bot"
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/lint-commit
            - general/lint-js
            - general/lint-json
            - general/lint-yaml
            - general/validate-js
            - general/build
            - general/test
          filters:
            branches:
              only: master
      - general/tag-and-publish-npm:
          context: NPM Publish - @eric.dahlseng
          git-ssh-fingerprint: 56:0f:82:9f:20:b1:3d:5e:03:b9:fe:40:b6:31:15:10
          git-user-email: edahlseng@users.noreply.github.com
          git-user-name: "Release Bot"
          npm-authentication-token: $NPM_AUTH_TOKEN
          requires:
            - general/lint-commit
            - general/lint-js
            - general/lint-json
            - general/lint-yaml
            - general/validate-js
            - general/build
            - general/test
          filters:
            branches:
              only: master
      - general/create-github-release:
          context: Release Bot
          github-access-token: $RELEASE_BOT_GITHUB_TOKEN
          requires:
            - general/tag-and-publish-npm
          filters:
            branches:
              only: master
